### ISSUE TITLE
Syntax error in configure script when building?

### ISSUE THREAD

**Issue by digitaltrousers** [karosium/smbusb#2]
Hi. Sorry if I've done something dumb, but ./configure fails for me. I believe I've installed all the prerequisites, and I've run
aclocal
libtoolize
autoconf
automake --add-missing
./configure
...and configure fails with the following:
root@kali:/usr/local/share/smbusb# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
./configure: line 11931: syntax error near unexpected token `0.22'
./configure: line 11931: `PKG_PROG_PKG_CONFIG(0.22)'

Thanks for any help.

**Comment by karosium** [comment]
Hi,
Do you have the pkg-config package installed?
I'll add it to the requirements if it's that. I think it was a default on my distro but it might not be on yours.

**Comment by digitaltrousers** [comment]
It wasn't installed, but installing it doesn't seem to have changed anything.

**Comment by karosium** [comment]
Did you re-run all the commands on a clean source tree afterwards? Installing pkg-config should've dropped the pkg.m4 file containing the PKG_PROG_PKG_CONFIG macro into the appropriate directory for aclocal to find it and merge it into the aclocal.m4 file it builds when you run it. If you can't find the macro in that file when you do a text search for it's name then it's file is either missing or aclocal is looking in the wrong place. [This](https://askubuntu.com/questions/468661/how-to-fix-pkg-prog-pkg-config-command-not-found-error#) may be helpful in that case.

**Comment by digitaltrousers** [comment]
Right you are!
I also had to manually copy firmware.h from the firmware directory to the lib directory to get it to build.
I also had the error loading the shared libraries, which you answered in issue#1.
Thanks heaps.

**Comment by karosium** [comment]
Hrmm.. it never should've gotten to a point where the manual firmware copy was necessary.. unless the sdcc checks passed but sdcc still couldn't build the firmware for some reason.. did you do 'git submodule update' to pull fx2lib into the tree after cloning? ( one of the things that git should probably either do automatically or at least display a message about IMO.. ) Either way, glad you got it to work.

**Comment by digitaltrousers** [comment]
I didn't know about 'git submodule update'. Thanks for the tip.
