### ISSUE TITLE
I am using degilent jtag usb cable,can it be supportted?

### ISSUE THREAD

**Issue by youxiaojie** [karosium/smbusb#20]
https://github.com/mithro/ixo-usb-jtag
I am using degilent jtag usb cable,can it be supportted?

**Comment by karosium** [comment]
If the cable uses the FX2 chip it **_should_** work.

The required lines won't be on the JTAG connector so you'll have to solder additional wires to the board and you'll also have to run ```smbusb_bootstrap``` with the digilent VID/PID every time you connect the cable (the other tools should work as-is after that.)

Good luck

**Comment by youxiaojie** [comment]
what is wire connexion between usb and fx2 and fx2 to i2c?

**Comment by karosium** [comment]
I'm not sure what you mean by "usb to fx2". If your Digilent cable works with https://github.com/mithro/ixo-usb-jtag then it has an FX2 chip on the PCB and the USB lines are connected to the USB connector.

Either way both are in the FX2 datasheet: https://www.cypress.com/file/138911/download

The chip's i2c lines will also be connected to the config eeprom which should provide easy access.

**Comment by youxiaojie** [comment]
it works with ixo-usb-jtag I mean which pin  of fx2 connected to which i2c‘s signal？

**Comment by karosium** [comment]
The hardware I2C bus pins of the FX2 chip are used (see SDA/SCL in the datasheet). They are already connected to the config eeprom so you can solder wires straight to the eeprom legs if you wish.

**Comment by youxiaojie** [comment]
ok. Will the battery's i2c address conflict with eeprom's address if I unconnect eeprom? what is the battery's address in common?

**Comment by karosium** [comment]
No conflict. SBS compliant battery will be at address 0x16/0x17, config eeprom is at 0xA0/0xA1.
