### ISSUE TITLE
connection issue - smbusb firmware error

### ISSUE THREAD

**Issue by NIVM1308** [karosium/smbusb#22]
Hi, 
I'm trying to compile the everything (, but I'm not sure it's correct.
Getting the following  message after make:

> ``Making all in firmware
make[1]: Entering directory '/home/jacob/Downloads/smbusb-master/firmware'
Makefile:17: warning: overriding recipe for target 'clean'
../fx2lib/lib/fx2.mk:100: warning: ignoring old recipe for target 'clean'
xxd -i build/smbusb_firmware.ihx firmware.h
cp firmware.h ../lib/firmware.h
make[1]: Leaving directory '/home/jacob/Downloads/smbusb-master/firmware'
Making all in lib
make[1]: Entering directory '/home/jacob/Downloads/smbusb-master/lib'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"libsmbusb\" -DPACKAGE_TARNAME=\"libsmbusb\" -DPACKAGE_VERSION=\"1.0.1\" -DPACKAGE_STRING=\"libsmbusb\ 1.0.1\" -DPACKAGE_BUGREPORT=\"contact@karosium.e4ward.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libsmbusb\" -DVERSION=\"1.0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DSTDC_HEADERS=1 -I.     -g -O2 -I/usr/include/libusb-1.0 -MT libsmbusb_la-smbusb.lo -MD -MP -MF .deps/libsmbusb_la-smbusb.Tpo -c -o libsmbusb_la-smbusb.lo `test -f 'smbusb.c' || echo './'`smbusb.c
libtool: compile:  gcc -DPACKAGE_NAME=\"libsmbusb\" -DPACKAGE_TARNAME=\"libsmbusb\" -DPACKAGE_VERSION=\"1.0.1\" "-DPACKAGE_STRING=\"libsmbusb 1.0.1\"" -DPACKAGE_BUGREPORT=\"contact@karosium.e4ward.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libsmbusb\" -DVERSION=\"1.0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DSTDC_HEADERS=1 -I. -g -O2 -I/usr/include/libusb-1.0 -MT libsmbusb_la-smbusb.lo -MD -MP -MF .deps/libsmbusb_la-smbusb.Tpo -c smbusb.c  -fPIC -DPIC -o .libs/libsmbusb_la-smbusb.o
smbusb.c: In function ‘SMBOpenDeviceVIDPID’:
smbusb.c:89:2: warning: ‘libusb_set_debug’ is deprecated: Use libusb_set_option instead [-Wdeprecated-declarations]
   89 |  libusb_set_debug(NULL, 0);
      |  ^~~~~~~~~~~~~~~~
In file included from smbusb.c:27:
/usr/include/libusb-1.0/libusb.h:1325:18: note: declared here
 1325 | void LIBUSB_CALL libusb_set_debug(libusb_context *ctx, int level);
      |                  ^~~~~~~~~~~~~~~~
smbusb.c: In function ‘SMBOpenDeviceBusAddr’:
smbusb.c:112:2: warning: ‘libusb_set_debug’ is deprecated: Use libusb_set_option instead [-Wdeprecated-declarations]
  112 |  libusb_set_debug(NULL, 0);
      |  ^~~~~~~~~~~~~~~~
In file included from smbusb.c:27:
/usr/include/libusb-1.0/libusb.h:1325:18: note: declared here
 1325 | void LIBUSB_CALL libusb_set_debug(libusb_context *ctx, int level);
      |                  ^~~~~~~~~~~~~~~~
libtool: compile:  gcc -DPACKAGE_NAME=\"libsmbusb\" -DPACKAGE_TARNAME=\"libsmbusb\" -DPACKAGE_VERSION=\"1.0.1\" "-DPACKAGE_STRING=\"libsmbusb 1.0.1\"" -DPACKAGE_BUGREPORT=\"contact@karosium.e4ward.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libsmbusb\" -DVERSION=\"1.0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DSTDC_HEADERS=1 -I. -g -O2 -I/usr/include/libusb-1.0 -MT libsmbusb_la-smbusb.lo -MD -MP -MF .deps/libsmbusb_la-smbusb.Tpo -c smbusb.c -o libsmbusb_la-smbusb.o >/dev/null 2>&1
mv -f .deps/libsmbusb_la-smbusb.Tpo .deps/libsmbusb_la-smbusb.Plo
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2 -I/usr/include/libusb-1.0 -version-info 1:1:0  -o libsmbusb.la -rpath /usr/local/lib libsmbusb_la-smbusb.lo libsmbusb_la-fxloader.lo  -lusb-1.0  -lusb-1.0
libtool: link: rm -fr  .libs/libsmbusb.a .libs/libsmbusb.la .libs/libsmbusb.lai .libs/libsmbusb.so .libs/libsmbusb.so.1 .libs/libsmbusb.so.1.0.1
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libsmbusb_la-smbusb.o .libs/libsmbusb_la-fxloader.o   -lusb-1.0  -g -O2   -Wl,-soname -Wl,libsmbusb.so.1 -o .libs/libsmbusb.so.1.0.1
libtool: link: (cd ".libs" && rm -f "libsmbusb.so.1" && ln -s "libsmbusb.so.1.0.1" "libsmbusb.so.1")
libtool: link: (cd ".libs" && rm -f "libsmbusb.so" && ln -s "libsmbusb.so.1.0.1" "libsmbusb.so")
libtool: link: ar cr .libs/libsmbusb.a  libsmbusb_la-smbusb.o libsmbusb_la-fxloader.o
libtool: link: ranlib .libs/libsmbusb.a
libtool: link: ( cd ".libs" && rm -f "libsmbusb.la" && ln -s "../libsmbusb.la" "libsmbusb.la" )
cp ../firmware/firmware.h .
make[1]: Leaving directory '/home/jacob/Downloads/smbusb-master/lib'
Making all in tools
make[1]: Entering directory '/home/jacob/Downloads/smbusb-master/tools'
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_bootstrap smbusb_bootstrap.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_bootstrap smbusb_bootstrap.o   ../lib/.libs/libsmbusb.so -lusb-1.0
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_sbsreport smbusb_sbsreport.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_sbsreport smbusb_sbsreport.o   ../lib/.libs/libsmbusb.so -lusb-1.0
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_bq8030flasher smbusb_bq8030flasher.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_bq8030flasher smbusb_bq8030flasher.o   ../lib/.libs/libsmbusb.so -lusb-1.0
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_r2j240flasher smbusb_r2j240flasher.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_r2j240flasher smbusb_r2j240flasher.o   ../lib/.libs/libsmbusb.so -lusb-1.0
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_m37512flasher smbusb_m37512flasher.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_m37512flasher smbusb_m37512flasher.o   ../lib/.libs/libsmbusb.so -lusb-1.0
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_scan smbusb_scan.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_scan smbusb_scan.o   ../lib/.libs/libsmbusb.so -lusb-1.0
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_comm smbusb_comm.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_comm smbusb_comm.o   ../lib/.libs/libsmbusb.so -lusb-1.0

> make[1]: Leaving directory '/home/jacob/Downloads/smbusb-master/tools'
make[1]: Entering directory '/home/jacob/Downloads/smbusb-master'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory `'/home/jacob/Downloads/smbusb-master'`

Then I'm running make install:

> > `Making` install in firmware
> make[1]: Entering directory '/home/jacob/Downloads/smbusb-master/firmware'
> Makefile:17: warning: overriding recipe for target 'clean'
> ../fx2lib/lib/fx2.mk:100: warning: ignoring old recipe for target 'clean'
> make[1]: Nothing to be done for 'install'.
> make[1]: Leaving directory '/home/jacob/Downloads/smbusb-master/firmware'
> Making install in lib
> make[1]: Entering directory '/home/jacob/Downloads/smbusb-master/lib'
> /bin/bash ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"libsmbusb\" -DPACKAGE_TARNAME=\"libsmbusb\" -DPACKAGE_VERSION=\"1.0.1\" -DPACKAGE_STRING=\"libsmbusb\ 1.0.1\" -DPACKAGE_BUGREPORT=\"contact@karosium.e4ward.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libsmbusb\" -DVERSION=\"1.0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DSTDC_HEADERS=1 -I.     -g -O2 -I/usr/include/libusb-1.0 -MT libsmbusb_la-smbusb.lo -MD -MP -MF .deps/libsmbusb_la-smbusb.Tpo -c -o libsmbusb_la-smbusb.lo `test -f 'smbusb.c' || echo './'`smbusb.c
> libtool: compile:  gcc -DPACKAGE_NAME=\"libsmbusb\" -DPACKAGE_TARNAME=\"libsmbusb\" -DPACKAGE_VERSION=\"1.0.1\" "-DPACKAGE_STRING=\"libsmbusb 1.0.1\"" -DPACKAGE_BUGREPORT=\"contact@karosium.e4ward.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libsmbusb\" -DVERSION=\"1.0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DSTDC_HEADERS=1 -I. -g -O2 -I/usr/include/libusb-1.0 -MT libsmbusb_la-smbusb.lo -MD -MP -MF .deps/libsmbusb_la-smbusb.Tpo -c smbusb.c  -fPIC -DPIC -o .libs/libsmbusb_la-smbusb.o
> smbusb.c: In function ‘SMBOpenDeviceVIDPID’:
> smbusb.c:89:2: warning: ‘libusb_set_debug’ is deprecated: Use libusb_set_option instead [-Wdeprecated-declarations]
>    89 |  libusb_set_debug(NULL, 0);
>       |  ^~~~~~~~~~~~~~~~
> In file included from smbusb.c:27:
> /usr/include/libusb-1.0/libusb.h:1325:18: note: declared here
>  1325 | void LIBUSB_CALL libusb_set_debug(libusb_context *ctx, int level);
>       |                  ^~~~~~~~~~~~~~~~
> smbusb.c: In function ‘SMBOpenDeviceBusAddr’:
> smbusb.c:112:2: warning: ‘libusb_set_debug’ is deprecated: Use libusb_set_option instead [-Wdeprecated-declarations]
>   112 |  libusb_set_debug(NULL, 0);
>       |  ^~~~~~~~~~~~~~~~
> In file included from smbusb.c:27:
> /usr/include/libusb-1.0/libusb.h:1325:18: note: declared here
>  1325 | void LIBUSB_CALL libusb_set_debug(libusb_context *ctx, int level);
>       |                  ^~~~~~~~~~~~~~~~
> libtool: compile:  gcc -DPACKAGE_NAME=\"libsmbusb\" -DPACKAGE_TARNAME=\"libsmbusb\" -DPACKAGE_VERSION=\"1.0.1\" "-DPACKAGE_STRING=\"libsmbusb 1.0.1\"" -DPACKAGE_BUGREPORT=\"contact@karosium.e4ward.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libsmbusb\" -DVERSION=\"1.0.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DSTDC_HEADERS=1 -I. -g -O2 -I/usr/include/libusb-1.0 -MT libsmbusb_la-smbusb.lo -MD -MP -MF .deps/libsmbusb_la-smbusb.Tpo -c smbusb.c -o libsmbusb_la-smbusb.o >/dev/null 2>&1
> mv -f .deps/libsmbusb_la-smbusb.Tpo .deps/libsmbusb_la-smbusb.Plo
> /bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2 -I/usr/include/libusb-1.0 -version-info 1:1:0  -o libsmbusb.la -rpath /usr/local/lib libsmbusb_la-smbusb.lo libsmbusb_la-fxloader.lo  -lusb-1.0  -lusb-1.0
> libtool: link: rm -fr  .libs/libsmbusb.a .libs/libsmbusb.la .libs/libsmbusb.lai .libs/libsmbusb.so .libs/libsmbusb.so.1 .libs/libsmbusb.so.1.0.1
> libtool: link: gcc -shared  -fPIC -DPIC  .libs/libsmbusb_la-smbusb.o .libs/libsmbusb_la-fxloader.o   -lusb-1.0  -g -O2   -Wl,-soname -Wl,libsmbusb.so.1 -o .libs/libsmbusb.so.1.0.1
> libtool: link: (cd ".libs" && rm -f "libsmbusb.so.1" && ln -s "libsmbusb.so.1.0.1" "libsmbusb.so.1")
> libtool: link: (cd ".libs" && rm -f "libsmbusb.so" && ln -s "libsmbusb.so.1.0.1" "libsmbusb.so")
> libtool: link: ar cr .libs/libsmbusb.a  libsmbusb_la-smbusb.o libsmbusb_la-fxloader.o
> libtool: link: ranlib .libs/libsmbusb.a
> libtool: link: ( cd ".libs" && rm -f "libsmbusb.la" && ln -s "../libsmbusb.la" "libsmbusb.la" )
> make[2]: Entering directory '/home/jacob/Downloads/smbusb-master/lib'
>  /bin/mkdir -p '/usr/local/lib'
>  /bin/bash ../libtool   --mode=install /usr/bin/install -c   libsmbusb.la '/usr/local/lib'
> libtool: install: /usr/bin/install -c .libs/libsmbusb.so.1.0.1 /usr/local/lib/libsmbusb.so.1.0.1
> libtool: install: (cd /usr/local/lib && { ln -s -f libsmbusb.so.1.0.1 libsmbusb.so.1 || { rm -f libsmbusb.so.1 && ln -s libsmbusb.so.1.0.1 libsmbusb.so.1; }; })
> libtool: install: (cd /usr/local/lib && { ln -s -f libsmbusb.so.1.0.1 libsmbusb.so || { rm -f libsmbusb.so && ln -s libsmbusb.so.1.0.1 libsmbusb.so; }; })
> libtool: install: /usr/bin/install -c .libs/libsmbusb.lai /usr/local/lib/libsmbusb.la
> libtool: install: /usr/bin/install -c .libs/libsmbusb.a /usr/local/lib/libsmbusb.a
> libtool: install: chmod 644 /usr/local/lib/libsmbusb.a
> libtool: install: ranlib /usr/local/lib/libsmbusb.a
> libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
> ----------------------------------------------------------------------
> 
> > Libraries` have been installed in:
>    /usr/local/lib
> If you ever happen to want to link against installed libraries
> in a given directory, LIBDIR, you must either use libtool, and
> specify the full pathname of the library, or use the '-LLIBDIR'
> flag during linking and do at least one of the following:
>    - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
>      during execution
>    - add LIBDIR to the 'LD_RUN_PATH' environment variable
>      during linking
>    - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
>    - have your system administrator add LIBDIR to '/etc/ld.so.conf'
> See any operating system documentation about shared libraries for
> more information, such as the ld(1) and ld.so(8) manual pages.
> ----------------------------------------------------------------------
> 
> >  /bin/mkdir -p '/usr/local/include'
>  /usr/bin/install -c -m 644 libsmbusb.h '/usr/local/include'
>  /bin/mkdir -p '/usr/local/lib/pkgconfig'
>  /usr/bin/install -c -m 644 libsmbusb.pc '/usr/local/lib/pkgconfig'
> make[2]: Leaving directory '/home/jacob/Downloads/smbusb-master/lib'
> make[1]: Leaving directory '/home/jacob/Downloads/smbusb-master/lib'
> Making install in tools
> make[1]: Entering directory '/home/jacob/Downloads/smbusb-master/tools'
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_bootstrap smbusb_bootstrap.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
> libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_bootstrap smbusb_bootstrap.o   ../lib/.libs/libsmbusb.so -lusb-1.0
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_sbsreport smbusb_sbsreport.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
> libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_sbsreport smbusb_sbsreport.o   ../lib/.libs/libsmbusb.so -lusb-1.0
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_bq8030flasher smbusb_bq8030flasher.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
> libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_bq8030flasher smbusb_bq8030flasher.o   ../lib/.libs/libsmbusb.so -lusb-1.0
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_r2j240flasher smbusb_r2j240flasher.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
> libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_r2j240flasher smbusb_r2j240flasher.o   ../lib/.libs/libsmbusb.so -lusb-1.0
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_m37512flasher smbusb_m37512flasher.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
> libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_m37512flasher smbusb_m37512flasher.o   ../lib/.libs/libsmbusb.so -lusb-1.0
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_scan smbusb_scan.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
> libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_scan smbusb_scan.o   ../lib/.libs/libsmbusb.so -lusb-1.0
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I../lib -g -O2 -I/usr/include/libusb-1.0   -o smbusb_comm smbusb_comm.o ../lib/libsmbusb.la -lusb-1.0  -lusb-1.0
> libtool: link: gcc -I../lib -g -O2 -I/usr/include/libusb-1.0 -o .libs/smbusb_comm smbusb_comm.o   ../lib/.libs/libsmbusb.so -lusb-1.0
> make[2]: Entering directory '/home/jacob/Downloads/smbusb-master/tools'
>  /bin/mkdir -p '/usr/local/bin'
>   /bin/bash ../libtool   --mode=install /usr/bin/install -c smbusb_bootstrap smbusb_sbsreport smbusb_bq8030flasher smbusb_r2j240flasher smbusb_m37512flasher smbusb_scan smbusb_comm '/usr/local/bin'
> libtool: install: /usr/bin/install -c .libs/smbusb_bootstrap /usr/local/bin/smbusb_bootstrap
> libtool: install: /usr/bin/install -c .libs/smbusb_sbsreport /usr/local/bin/smbusb_sbsreport
> libtool: install: /usr/bin/install -c .libs/smbusb_bq8030flasher /usr/local/bin/smbusb_bq8030flasher
> libtool: install: /usr/bin/install -c .libs/smbusb_r2j240flasher /usr/local/bin/smbusb_r2j240flasher
> libtool: install: /usr/bin/install -c .libs/smbusb_m37512flasher /usr/local/bin/smbusb_m37512flasher
> libtool: install: /usr/bin/install -c .libs/smbusb_scan /usr/local/bin/smbusb_scan
> libtool: install: /usr/bin/install -c .libs/smbusb_comm /usr/local/bin/smbusb_comm
> 
> > make[2]:` Nothing to be done for 'install-data-am'.
> make[2]: Leaving directory '/home/jacob/Downloads/smbusb-master/tools'
> make[1]: Leaving directory '/home/jacob/Downloads/smbusb-master/tools'
> make[1]: Entering directory '/home/jacob/Downloads/smbusb-master'
> make[2]: Entering directory '/home/jacob/Downloads/smbusb-master'
> make[2]: Nothing to be done for 'install-exec-am'.
> make[2]: Nothing to be done for 'install-data-am'.
> make[2]: Leaving directory '/home/jacob/Downloads/smbusb-master'
> make[1]: Leaving directory '/home/jacob/Downloads/smbusb-master'
> 

And then I'm trying to run smbusb_scan -a and getting: 

> `------------------------------------
>              smbusb_scan
> ------------------------------------
> Error: Unable to open device. (insufficient permissions? connection issue?)`
> 
> 

My device is connected though, do you know what might be the problem?

**Comment by karosium** [comment]
Hi

Build seems fine. Does running the tool as root change anything?
What do you get when running lsusb?

**Comment by karosium** [comment]
Closing for now, feel free to comment if this is still relevant.
