### ISSUE TITLE
Can we use this solution to reset a laptop battery?

### ISSUE THREAD

**Issue by cptX** [karosium/smbusb#23]
Hi, can we use this solution to reset / reprogram a laptop battery?
It' s not clear to me if this is only for reading the data of the battery or being able to write to the chip too.

**Comment by karosium** [comment]
There are tools for reading and writing raw binary images of the program and data flash on the controllers but changing those to achieve a desired effect is up to the user.
You can find more information in the original blog posts linked at the bottom of http://www.karosium.com/p/smbusb.html and the comments left on them.

**Comment by cptX** [comment]
So is your solution here able to write to the chip (to the SMBUS in general)?

**Comment by karosium** [comment]
This project has tools that can read, erase and write flash memory on bq8030, m37512 and r2j240 battery controller chips via SMBus when the chips are in bootrom mode. It's not a generic tool if that's what you mean.
