### ISSUE TITLE
error on loading firmware

### ISSUE THREAD

**Issue by dumpfnase** [karosium/smbusb#3]
Hi,

i'm new to this, so i might have screwed something but:

compiling fo the tools and the firmware went fine but i get an error, when i try to start smbusb_scan or any of the other tools:

```
# smbusb_scan -w 0x16
------------------------------------
             smbusb_scan
------------------------------------
Error Opening SMBusb: libusb error: -1
```

in "dmesg" i can see some more error messages:

```
usb 3-2.1: USB disconnect, device number 62
kernel: usb 3-2.1: new high-speed USB device number 63 using xhci_hcd
kernel: usb 3-2.1: device descriptor read/64, error -110
kernel: usb 3-2.1: device descriptor read/64, error -110
kernel: usb 3-2.1: new high-speed USB device number 64 using xhci_hcd
kernel: usb 3-2.1: device descriptor read/64, error -110
kernel: usb 3-2.1: device descriptor read/64, error -110
kernel: usb 3-2.1: new high-speed USB device number 65 using xhci_hcd
kernel: usb 3-2.1: device descriptor read/8, error -110
kernel: usb 3-2.1: device descriptor read/8, error -110
kernel: usb 3-2.1: new high-speed USB device number 66 using xhci_hcd
kernel: usb 3-2.1: device descriptor read/8, error -71
kernel: usb 3-2.1: device descriptor read/8, error -71
kernel: usb 3-2-port1: unable to enumerate USB device
kernel: usb 3-2.1: new full-speed USB device number 67 using xhci_hcd
kernel: usb 3-2.1: device descriptor read/64, error -32
```

i do get the same behavior when i try to load the firmware manually with "fxload":

`fxload -t fx2lp -v -I /home/sol/Downloads/smbusb-master/firmware/build/smbusb_firmware.ihx -D /dev/bus/usb/003/069`

So, i guess something is wrong with my firmware?
Have you ever seen this?
Any idea what might have gone wrong?

Thanks a lot,
Hans

**Comment by karosium** [comment]
Hi,

That seems to me like a bad board. If you never saw it enumerate properly you should probably buy a new one (or maybe try trouble-shooting the board under a microscope/magnifying lens, it could be a simple soldering issue).  It should come up as a Cypress FX2LP Development Board device by default, firmware load makes it re-enumerate as SMBusb.

**Comment by dumpfnase** [comment]
Hi,

thanks for your response, but it seems you are wrong. 
As firmware loading with sigrok is OK the board seems to work!

My brother was digging into it and made a small patch for fx2lib to make it work.

here is his patch file:

```
diff --git a/lib/fx2.mk b/lib/fx2.mk
index d876a6d..c404ce0 100644
--- a/lib/fx2.mk
+++ b/lib/fx2.mk
@@ -41,11 +41,11 @@ VID?=0x04b4
 PID?=0x8613
 
 INCLUDES?=""
-DSCR_AREA?=-Wl"-b DSCR_AREA=0x3e00"
-INT2JT?=-Wl"-b INT2JT=0x3f00"
-CODE_SIZE?=--code-size 0x3c00
+DSCR_AREA?=-Wl"-b DSCR_AREA=0x1e00"
+INT2JT?=-Wl"-b INT2JT=0x1f00"
+CODE_SIZE?=--code-size 0x1c00
 XRAM_SIZE?=--xram-size 0x0200
-XRAM_LOC?=--xram-loc 0x3c00
+XRAM_LOC?=--xram-loc 0x1c00
 BUILDDIR?=build
 
 FX2LIBDIR?=$(dir $(lastword $(MAKEFILE_LIST)))../
```

I don't understand why it's necessary, but it works!

Thanks,
Hans

**Comment by karosium** [comment]
Oh okay, the bus/device addressing you had in the fxload command had me confused. I thought you were doing it that way because it never enumerated properly from the get go.

Interesting, it seems like sigrok has the addresses in your patch for most hardware it builds firmware for but it also uses the default ones in fx2lib for a few. Since there are devices using the same variant of the same chip but different address configs I suspect it's something in the config eeprom that's causing the addresses to change. I don't want to fork fx2lib but I'll probably add the patch to the repo for use with logic analyzers.

Can you tell me what product/board you were using?

Thanks

**Comment by dumpfnase** [comment]
Hi,

well my board - i bought it in eBay

lsusb show it is this one: 

`Bus 003 Device 024: ID 04b4:8613 Cypress Semiconductor Corp. CY7C68013 EZ-USB FX2 USB 2.0 Development Kit`

does it help?

**Comment by karosium** [comment]
Hrmm
I have no clue why it doesn't work with your board then. However both patched and unpatched works on mine and since sigrok uses the patched values for almost everything I'm just going to apply it automatically in configure from now on.

Thanks for reporting! Closed

**Comment by loki-amorf** [comment]
I confirm the presence of this problem. Where you were before, I had to come to the solution of this problem on my own.
