### ISSUE TITLE
Scanning only works once

### ISSUE THREAD

**Issue by schadEigentlich** [karosium/smbusb#7]
smbusb_scan -a only seems to work until it finds my controller (bq8030), after that it always comes back with ERROR -9.
First scan:

`------------------------------------
             smbusb_scan
------------------------------------
SMBusb Firmware Version: 1.0.1
Scanning for addresses..
Scan range: 00 - ff
Skipping: a0 a1 
------------------------------------
[16] ACK
[17] ACK
[19] ERROR: -9
[1a] ERROR: -9
[1b] ERROR: -9
[1c] ERROR: -9
[1d] ERROR: -9
[1e] ERROR: -9
[1f] ERROR: -9
`

Starting another scan after that:

`------------------------------------
             smbusb_scan
------------------------------------
SMBusb Firmware Version: 1.0.1
Scanning for addresses..
Scan range: 00 - ff
Skipping: a0 a1 
------------------------------------
[0] ERROR: -9
[1] ERROR: -9
[2] ERROR: -9
[3] ERROR: -9
[4] ERROR: -9
[5] ERROR: -9
[6] ERROR: -9
[7] ERROR: -9
[8] ERROR: -9
[9] ERROR: -9
[a] ERROR: -9
[b] ERROR: -9
[c] ERROR: -9
[d] ERROR: -9
[e] ERROR: -9
[f] ERROR: -9
[10] ERROR: -9
[11] ERROR: -9
[12] ERROR: -9
[13] ERROR: -9
[14] ERROR: -9
[15] ERROR: -9
[16] ERROR: -9
[17] ERROR: -9
`  
Every time I plug in the FX2 it will work exactly once. I tested it on my laptop running Manjaro and on a Raspberry Pi 2.

**Comment by karosium** [comment]
Well, that's weird.

LIBUSB_ERROR_PIPE = -9,
LIBUSB_ERROR_PIPE if the control request was not supported by the device 

You seem to be the first one to encounter this issue so I'm inclined to believe it's something to do with your FX2 board or specific battery pack. 
Does it recover if you remove and reattach power to (or just reset) the battery controller while keeping the FX2 powered? What happens when you try a write scan? (smbusb_scan -w 0x16)

**Comment by karosium** [comment]
If anyone else is getting this please comment. Otherwise I'll close as can't repro next month.

**Comment by climber64** [comment]
Sorry for this late reply on this issue. But I have the same problem with this board. I work under mint 20.2 up to date. With test soft cycfx2prog run the board perfect see: http://www.colecovision.eu/mcs51/CY7C68013A%20EZ-USB%20FX2LP%20USB2.0%20Development%20Board%20LED.shtml
But when I compile the smbusb software I have this error: -9. I have no idea what can I do, please can you help me? What for more Info you must have? Thanks in advance.
